### ISSUE TITLE
why handle data-* and aria-* as properties

### ISSUE THREAD

**Issue by neonstalwart** [nthtran/vdom-to-html#11]
data-* and aria-* should be handled as attributes rather than have a special case for them as properties.  

https://github.com/nthtran/vdom-to-html/blob/fe04172917f596dc4b24a4b0dc20c747c9454144/test/test.js#L58-L64 is currently

```js
  it('should render `data-` and `aria-` properties', function () {
    var node = new VNode('web-component', {
      'data-click': 'clicked!',
      'aria-labelledby': 'label'
    });
    assert.equal(toHTML(node), '<web-component data-click="clicked!" aria-labelledby="label"></web-component>');
  });
```

these shouldn't need to be handled as a special case in properties because it is inconsistent with what virtual-dom does and so any rendering code which uses these as attributes will not produce the same results in the browser.  as attributes these don't need any special handling.

```js
  it('should render `data-` and `aria-` attributes', function () {
    var node = new VNode('web-component', {
      attributes: {
        'data-click': 'clicked!',
        'aria-labelledby': 'label'
      }
    });
    assert.equal(toHTML(node), '<web-component data-click="clicked!" aria-labelledby="label"></web-component>');
  });
```

is this something you want to continue to support or are you open to dropping them?

**Comment by bitinn** [comment]
I am ok with dropping it, seems like we should use `attributes` anyway and it works.

ref: https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md#custom-attributes-data-

**Comment by nthtran** [comment]
Agreed. Support for these is dropped in v2.0.0.
