### ISSUE TITLE
itemProp, itemScope, itemType casing

### ISSUE THREAD

**Issue by wooorm** [nthtran/vdom-to-html#16]
This one really got me: `vdom-to-html` ignores these three microdata properties when lower-cased.
[`property-config.js`](https://github.com/nthtran/vdom-to-html/blob/c6bed5ae9fd3bcfb6cfe88f96cc68140298a964e/property-config.js#L133-L135) uses camel-cased properties, but I cannot find any reason for those when peeking through [schema.org](https://schema.org/docs/gs.html).

Is this intentional? Am I missing something? Or, is this a bug?

**Comment by nthtran** [comment]
This is indeed intentional. What you set directly on a `VNode` are properties and not attributes, thus the camel casing. Please see [docs on VNode](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md).

**Comment by wooorm** [comment]
[Found it](http://www.w3.org/TR/microdata/#dom-itemscope)! Thanks :)
