### ISSUE TITLE
please add a 'beautify' option

### ISSUE THREAD

**Issue by iambumblehead** [nthtran/vdom-to-html#21]
please add a 'beautify' option to return html that formatted with line breaks and indentation

**Comment by nthtran** [comment]
I don't really have time for this right now. Would you like to contribute a PR @iambumblehead?

**Comment by iambumblehead** [comment]
I'll let you know if/when I try to work on something for a pr

**Comment by iambumblehead** [comment]
The ['html' package on npm][0] does a fine job for me
```javascript
html = require('html');
html.prettyPrint( vdomtohtml(vnode) );
```

[0]: https://www.npmjs.com/package/html
