### ISSUE TITLE
dataset property is ignored.

### ISSUE THREAD

**Issue by fiatjaf** [nthtran/vdom-to-html#22]
Shouldn't `toHTML(h('div', {dataset: {key: 'value'}}))` render to `<div data-key="value"></div>`? Today it is giving `<div></div>`, although `toHTML(h('div', {attributes: {'data-key': 'value'}}))` works.

**Comment by tdumitrescu** [comment]
+1. Proposed a fix in https://github.com/nthtran/vdom-to-html/pull/23.
