### ISSUE TITLE
No "escape hatch" for inserting raw HTML into a node

### ISSUE THREAD

**Issue by r24y** [nthtran/vdom-to-html#24]
I'm interested in rendering Markdown files using this library, but reading the code it seems impossible, even if I use a Widget or a Hook.

**Comment by nthtran** [comment]
Have you tried `innerHTML`?

**Comment by r24y** [comment]
Oh, I'm so embarrassed. I forgot that `virtual-dom` worked by setting properties on the DOM node itself. Thanks for your help!

**Comment by nthtran** [comment]
No worries :)
