### ISSUE TITLE
consider handling svg?

### ISSUE THREAD

**Issue by bitinn** [nthtran/vdom-to-html#3]
Since `virtual-dom` 1.1 added better support for svg attributes, though our use-case doesn't require changing svg content, innerHTML works fine for now.

**Comment by nthtran** [comment]
But `vdom-to-html` does work with `virtual-dom/virtual-hyperscript/svg`?

**Comment by bitinn** [comment]
hmm, you are right, just found out `h('svg', { namespace: 'http://www.w3.org/2000/svg', 'viewBox': '0 0 24 24' })` is not the same as `svg('svg', { 'viewBox': '0 0 24 24' })`, viewBox are set as properties.attributes.viewBox not properties.viewBox.
