### ISSUE TITLE
charset shouldn't be charSet

### ISSUE THREAD

**Issue by bitinn** [nthtran/vdom-to-html#4]
Discovered this when I try to convert `h('meta', { charset: 'UTF-8' })` to no avail.

I don't know why React is doing that, but I can't think of any instance where `charSet` is used in DOM, they should all be `charset`. Maybe React has different behaviour internally? Can't tell from [related pull request](https://github.com/facebook/react/pull/293).

In DOM:

![screen shot 2015-01-14 at 11 30 17 pm](https://cloud.githubusercontent.com/assets/1484279/5741337/673bb1f2-9c45-11e4-8eca-43a2ba54846a.png)

**Comment by bitinn** [comment]
I was referring to this by the way: https://github.com/nthtran/vdom-to-html/blob/master/property-config.js#L34

There are maybe other pitfall, maybe cross check with [html-attributes](https://github.com/alexmingoia/html-attributes/blob/master/lib/html-attributes.js) and other official source?

**Comment by nthtran** [comment]
Thank you. This is fixed in v1.2.3.

I also updated the list with more properties. Please let me know if you find things like this again!
