### ISSUE TITLE
doesn't render custom attributes

### ISSUE THREAD

**Issue by jesseditson** [nthtran/vdom-to-html#6]
This looks like it's by design - I see a test that verifies that it doesn't render custom attributes here:

https://github.com/nthtran/vdom-to-html/blob/master/test/test.js#L41

Wondering what the motivation behind this is, as I'd like to use this library without removing custom attributes.

**Comment by nthtran** [comment]
For custom attributes you can do this:

```js
h('div', {
  attributes: { 'custom-attribute': 'value' }
})
```

**Comment by jesseditson** [comment]
Interesting - I'm using [html-to-vdom](https://github.com/TimBeyer/html-to-vdom) to serialize html that includes custom attributes, which sets them as properties.

I also noticed that [virtual-dom-stringify](https://github.com/alexmingoia/virtual-dom-stringify) *does* render custom attribtues when they are set as properties on a vnode.

I'm curious if @Matt-Esch or @raynos can weigh in here - what is the intended behavior with virtual-dom? Should html-to-vdom be serializing to attributes, or should vdom-to-html be rendering custom properties?

**Comment by jesseditson** [comment]
After exploring, it looks like I should be filing this issue on [html-to-vdom](https://github.com/TimBeyer/html-to-vdom), as it's just grabbing all properties and putting them at the root level of attributes. I think this library is correct and the others are incorrect, as I think invalid root properties will be skipped when rendering in a DOM.

**Comment by nthtran** [comment]
Yeah `virtual-dom` doesn't render to the DOM custom attributes set on `properties`. That's why this library doesn't support thatt.
