### ISSUE TITLE
All attribute hooks are not rendered

### ISSUE THREAD

**Issue by marlun** [nthtran/vdom-to-html#9]
I'm having some problems with value attribute being rendered as [object Object] instead of its actual value. This is because a soft hook is created and the following code does not render it because of the second condition `value.namespace`.

```javascript
if (isVHook(value) && value.namespace) {
   ret += ' ' + createAttribute(name, value.value, true);
   continue;
}
```

As an example this test fails if added:

```javascript
it('should render hooks', function () {
  var node = h('input', { type: 'submit', value: 'add' });
  assert.equal(toHTML(node), '<input type="submit" value="add">');
});
```

**Comment by bitinn** [comment]
@marlun let me know if the pull request help.

**Comment by nthtran** [comment]
@marlun let us know if it works for you now

**Comment by marlun** [comment]
Just so that other people can see, I answered in #10 and everything is working fine.
